---
# # VM: https://github.com/jdauphant/ansible-role-kvm/blob/master/templates/vm.kvm.libvirt.xml.j2
# # /var/lib/libvirt/images/rhcos42.qcow2
# # /var/lib/libvirt/images/CentOS-7-x86_64-GenericCloud.qcow2
- name: Create disk for {{ vm_instance_name }}
  command: "qemu-img create -f qcow2 -b {{ coreos_image_location }} /var/lib/libvirt/images/{{ vm_instance_name }}.qcow2 {{ vm_root_disk_size }}"
  args:
    creates: "/var/lib/libvirt/images/{{ vm_instance_name }}.qcow2"

- name: Copy ignition {{ vm_instance_name }}
  copy:
    src: "{{ vm_ignition_file }}"
    dest: "/var/lib/libvirt/images/{{ vm_instance_name }}.ign"
    mode: '0644'

- name: Create disk for OpenShift Container Storage 10GB
  command: "qemu-img create -f qcow2 /var/lib/libvirt/images/{{ vm_instance_name }}-ocs-1.qcow2 {{ ocs_disk_size_1 }}"
  args:
    creates: "/var/lib/libvirt/images/{{ vm_instance_name }}-ocs-1.qcow2"
  when: install_ocs == true

- name: Create disk for OpenShift Container Storage 100GB
  command: "qemu-img create -f qcow2 /var/lib/libvirt/images/{{ vm_instance_name }}-ocs-2.qcow2 {{ ocs_disk_size_2 }}"
  args:
    creates: "/var/lib/libvirt/images/{{ vm_instance_name }}-ocs-2.qcow2"
  when: install_ocs == true

# - name: Debug - create /tmp/{{ vm_instance_name }}.virt.xml
#   template:
#     src: "vm.xml.j2"
#     dest: "/tmp/{{ vm_instance_name }}.virt.xml"

- name: Define VirtualMachine {{ vm_instance_name }}
  virt:
    name: "{{ vm_instance_name }}"
    command: define
    xml: "{{ lookup('template', 'templates/vm.xml.j2') }}"

- name: Start VirtualMachine {{ vm_instance_name }}
  virt: 
    name: "{{ vm_instance_name }}"
    state: running
    autostart: "{{ vm_autostart }}"
