---
- name: Destroy VM {{ vm_instance_name }}
  virt:
    command: destroy
    name: "{{ vm_instance_name }}"
  ignore_errors: yes

- name: Undefine VM {{ vm_instance_name }}
  virt:
    command: undefine
    name: "{{ vm_instance_name }}"
  ignore_errors: yes

- name: Delete disk {{ vm_instance_name }}
  file:
    path: "/var/lib/libvirt/images/{{ vm_instance_name }}.qcow2"
    state: absent

- name: Delete ignition {{ vm_instance_name }}
  file:
    path: "/var/lib/libvirt/images/{{ vm_instance_name }}.ign"
    state: absent

- name: Delete OpenShift Container Storage 10GB {{ vm_instance_name }}
  file:
    path: "/var/lib/libvirt/images/{{ vm_instance_name }}-ocs-1.qcow2"
    state: absent

- name: Delete OpenShift Container Storage 100GB {{ vm_instance_name }}
  file:
    path: "/var/lib/libvirt/images/{{ vm_instance_name }}-ocs-2.qcow2"
    state: absent
